Une KPI (Key Performance Indicator) Une métrique permettant de mesurant l’avancement ou la performance

In [1]:
import pandas as pd, numpy as npy

In [3]:
data = pd.read_csv("/home/camelia/M2/Eval1/eval_data.csv")

In [4]:
data.head(10)

,Unnamed: 0,order_id,quantity,item_name,choice_description,item_price
0,0,1,1,Chips and Fresh Tomato Salsa,NaN,NaN
1,1,1,1,Izze,[Clementine],$3.39
2,2,1,1,Nantucket Nectar,[Apple],$3.39
3,3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,NaN
4,4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,6,3,1,Side of Chips,NaN,$1.69
7,7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [10]:
data.size

27732

In [9]:
data.ndim

2

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          4622 non-null   int64
 1   order_id            4622 non-null   int64
 2   quantity            4622 non-null   int64
 3   item_name           4622 non-null   object
 4   choice_description  3376 non-null   object
 5   item_price          4522 non-null   object
dtypes: int64(3), object(3)
memory usage: 216.8+ KB

In [7]:
data.describe()

        Unnamed: 0     order_id     quantity
count  4622.000000  4622.000000  4622.000000
mean   2310.500000   927.254868     1.075725
std    1334.400802   528.890796     0.410186
min       0.000000     1.000000     1.000000
25%    1155.250000   477.250000     1.000000
50%    2310.500000   926.000000     1.000000
75%    3465.750000  1393.000000     1.000000
max    4621.000000  1834.000000    15.000000

In [12]:
data['item_name'].value_counts()

Chicken Bowl                             726
Chicken Burrito                          553
Chips and Guacamole                      479
Steak Burrito                            368
Canned Soft Drink                        301
Steak Bowl                               211
Chips                                    211
Bottled Water                            162
Chicken Soft Tacos                       115
Chips and Fresh Tomato Salsa             110
Chicken Salad Bowl                       110
Canned Soda                              104
Side of Chips                            101
Veggie Burrito                            95
Barbacoa Burrito                          91
Veggie Bowl                               85
Carnitas Bowl                             68
Barbacoa Bowl                             66
Carnitas Burrito                          59
Steak Soft Tacos                          55
6 Pack Soft Drink                         54
Chips and Tomatillo Red Chili Salsa       48
Chicken Crispy Tacos                      47
Chips and Tomatillo Green Chili Salsa     43
Carnitas Soft Tacos                       40
Steak Crispy Tacos                        35
Chips and Tomatillo-Green Chili Salsa     31
Steak Salad Bowl                          29
Nantucket Nectar                          27
Barbacoa Soft Tacos                       25
Chips and Roasted Chili Corn Salsa        22
Izze                                      20
Chips and Tomatillo-Red Chili Salsa       20
Veggie Salad Bowl                         18
Chips and Roasted Chili-Corn Salsa        18
Barbacoa Crispy Tacos                     11
Barbacoa Salad Bowl                       10
Chicken Salad                              9
Carnitas Crispy Tacos                      7
Veggie Soft Tacos                          7
Veggie Salad                               6
Carnitas Salad Bowl                        6
Burrito                                    6
Steak Salad                                4
Crispy Tacos                               2
Salad                                      2
Bowl                                       2
Veggie Crispy Tacos                        1
Chips and Mild Fresh Tomato Salsa          1
Carnitas Salad                             1
Name: item_name, dtype: int64

In [15]:
data.groupby(['item_name']).count()

,Unnamed: 0,order_id,quantity,choice_description,item_price
item_name,,,,,
6 Pack Soft Drink,54,54,54,54,54
Barbacoa Bowl,66,66,66,66,66
Barbacoa Burrito,91,91,91,91,91
Barbacoa Crispy Tacos,11,11,11,11,11
Barbacoa Salad Bowl,10,10,10,10,10
Barbacoa Soft Tacos,25,25,25,25,25
Bottled Water,162,162,162,0,162
Bowl,2,2,2,2,2
Burrito,6,6,6,6,6
Canned Soda,104,104,104,104,104
Canned Soft Drink,301,301,301,301,301
Carnitas Bowl,68,68,68,68,68
Carnitas Burrito,59,59,59,59,59
Carnitas Crispy Tacos,7,7,7,7,7
Carnitas Salad,1,1,1,1,1
Carnitas Salad Bowl,6,6,6,6,6
Carnitas Soft Tacos,40,40,40,40,40
Chicken Bowl,726,726,726,726,726
Chicken Burrito,553,553,553,553,553
Chicken Crispy Tacos,47,47,47,47,47
Chicken Salad,9,9,9,9,9
Chicken Salad Bowl,110,110,110,110,110
Chicken Soft Tacos,115,115,115,115,115
Chips,211,211,211,0,211
Chips and Fresh Tomato Salsa,110,110,110,0,74
Chips and Guacamole,479,479,479,0,479
Chips and Mild Fresh Tomato Salsa,1,1,1,0,1
Chips and Roasted Chili Corn Salsa,22,22,22,0,22
Chips and Roasted Chili-Corn Salsa,18,18,18,0,0
Chips and Tomatillo Green Chili Salsa,43,43,43,0,43
Chips and Tomatillo Red Chili Salsa,48,48,48,0,48
Chips and Tomatillo-Green Chili Salsa,31,31,31,0,2
Chips and Tomatillo-Red Chili Salsa,20,20,20,0,3
Crispy Tacos,2,2,2,2,2
Izze,20,20,20,20,20
Nantucket Nectar,27,27,27,27,27
Salad,2,2,2,2,2
Side of Chips,101,101,101,0,101
Steak Bowl,211,211,211,211,211
Steak Burrito,368,368,368,368,368
Steak Crispy Tacos,35,35,35,35,35
Steak Salad,4,4,4,4,4
Steak Salad Bowl,29,29,29,29,29
Steak Soft Tacos,55,55,55,55,55
Veggie Bowl,85,85,85,85,85
Veggie Burrito,95,95,95,95,95
Veggie Crispy Tacos,1,1,1,1,1
Veggie Salad,6,6,6,6,6
Veggie Salad Bowl,18,18,18,18,18
Veggie Soft Tacos,7,7,7,7,7